      name: Execução de testes regressivos

      on:
        push:
          branches: [ "master" ]
        pull_request:
          branches: [ "master" ]
        schedule:
          - cron: '0 9 * * 1-5'

      jobs:
        build:

          runs-on: ubuntu-latest

          steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml

            - name: Run tests
              run: mvn test -Dgroups="regressivo", -DBrowser="HEADLESS"

            - name: Get Allure history
                uses: actions/checkout@v3
                if: always()
                continue-on-error: true
                with:
                  ref: gh-pages
                  path: gh-pages

            - name: Allure Report Test marketplace action
                uses: simple-elf/allure-report-action@master
                if: always()
                id: allure-report
                with:
                  allure_results: allure-results
                  gh_pages: gh-pages
                  allure_report: allure-report
                  allure_history: allure-history

            - name: Deploy report to Github Pages
                if: always()
                uses: peaceiris/actions-gh-pages@v2
                env:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: allure-history

